name: "Deploy to Netlify"

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Installeer alle packages
      run: npm i
    - name: Voer testen uit
      run: npm run test
    - name: Bouw project
      run: npm run build

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_SECRET }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_ID }}
      with:
        args: deploy --dir=dist/apps/gessit-app
        secrets: '["NETLIFY_SECRET", "NETLIFY_ID"]'